import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

export const downloadPurchaseOrderPDF = (order: any) => {
  const doc = new jsPDF()

  // Add Logo / Header
  doc.setFontSize(20)
  doc.setTextColor(40)
  doc.text("PURCHASE ORDER", 14, 22)
  
  doc.setFontSize(10)
  doc.text(`PO Number: ${order.poNumber}`, 14, 32)
  doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, 14, 38)
  doc.text(`Status: ${order.status}`, 14, 44)

  // Buyer Info
  doc.setFontSize(12)
  doc.text("Buyer Information", 14, 56)
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(order.buyerCompany, 14, 62)
  doc.text(order.buyerName, 14, 68)
  doc.text(order.buyerEmail, 14, 74)
  if (order.buyerPhone) doc.text(order.buyerPhone, 14, 80)
  doc.text(`${order.buyerCountry} - ${order.buyerAddress || ''}`, 14, 86)

  // Shipment Details (right side)
  doc.setTextColor(40)
  doc.setFontSize(12)
  doc.text("Shipment Details", 120, 56)
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text(`Incoterms: ${order.incoterms || 'FOB'}`, 120, 62)
  doc.text(`Port of Loading: ${order.portOfLoading || 'Nhava Sheva, India'}`, 120, 68)
  if (order.destinationPort) doc.text(`Destination: ${order.destinationPort}`, 120, 74)
  doc.text(`Method: ${order.shipmentMethod || 'Sea'}`, 120, 80)

  // Table
  const tableColumn = ["Product", "Quantity", "Unit Price", "Amount"]
  const tableRows: any[] = []

  order.items.forEach((item: any) => {
    const itemData = [
      item.productName,
      `${item.quantity} ${item.unit}`,
      `${item.currency || 'USD'} ${item.unitPrice}`,
      `${item.currency || 'USD'} ${item.amount}`
    ]
    tableRows.push(itemData)
  })

  autoTable(doc, {
    startY: 100,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255 }
  })

  // Financials
  const finalY = (doc as any).lastAutoTable.finalY || 100
  doc.text(`Subtotal: ${order.currency || 'USD'} ${order.subtotal?.toLocaleString()}`, 140, finalY + 10)
  if (order.gstAmount > 0) {
    doc.text(`GST: ${order.currency || 'USD'} ${order.gstAmount?.toLocaleString()}`, 140, finalY + 16)
  }
  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.text(`Total: ${order.currency || 'USD'} ${order.totalAmount?.toLocaleString()}`, 140, finalY + 26)

  // Footer / Terms
  doc.setFontSize(9)
  doc.setTextColor(150)
  doc.text("Generated by Aiva Enterprises", 14, 280)

  // Save the PDF
  doc.save(`${order.poNumber}.pdf`)
}
